Repository appuio/appuio-io-docs, pull requests merged in 2021-09, with the labels that each got.

#18 Define naming scheme for domains and zones
  docs/antora.yml
  docs/modules/ROOT/pages/references/dns-naming-scheme.adoc
  docs/modules/ROOT/pages/references/quality-requirements/usability/dns-naming-scheme.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#19 Add how-to page to configure Keycloak brokering
  docs/modules/ROOT/assets/images/how-to/keycloak-brokering.drawio.svg
  docs/modules/ROOT/pages/how-to/keycloak-brokering.adoc
  docs/modules/ROOT/pages/how-to/keycloak-setup.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: change

#20 Add security requirement: Impersonating cluster-admin
  docs/modules/ROOT/pages/references/quality-requirements/security/impersonating-cluster-admin.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#22 Reformat decision documents
  docs/modules/ROOT/pages/explanation/decisions/arbitrary-usernames.adoc
  docs/modules/ROOT/pages/explanation/decisions/keycloak.adoc
  docs/modules/ROOT/pages/explanation/decisions/kyverno-generator.adoc
  docs/modules/ROOT/pages/explanation/decisions/kyverno-policy.adoc
  docs/modules/ROOT/pages/explanation/decisions/stable-usernames.adoc
  docs/modules/ROOT/pages/explanation/decisions/usernames.adoc
Labels: change

#21 Add decision: IdP group membership mapping
  docs/antora.yml
  docs/modules/ROOT/assets/images/how-to/keycloak-brokering.drawio.svg
  docs/modules/ROOT/pages/explanation/decisions/idp-group-mapping.adoc
  docs/modules/ROOT/pages/explanation/decisions/keycloak.adoc
  docs/modules/ROOT/pages/explanation/system/idea.adoc
  docs/modules/ROOT/pages/how-to/keycloak-setup.adoc
  docs/modules/ROOT/pages/references/architecture/openshift-authentication.adoc
  docs/modules/ROOT/pages/references/quality-requirements/usability/user-arbitrary-name.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#26 Delete unneeded images
  docs/modules/ROOT/assets/images/chrome.svg
  docs/modules/ROOT/assets/images/cloudflare.svg
  docs/modules/ROOT/assets/images/cncf.svg
  docs/modules/ROOT/assets/images/cri-o.svg
  docs/modules/ROOT/assets/images/digital-ocean.svg
  docs/modules/ROOT/assets/images/docker-hub.svg
  docs/modules/ROOT/assets/images/docker.svg
  docs/modules/ROOT/assets/images/dropbox.svg
  docs/modules/ROOT/assets/images/git.svg
  docs/modules/ROOT/assets/images/gmail.svg
  docs/modules/ROOT/assets/images/golang.svg
  docs/modules/ROOT/assets/images/heroku.svg
  docs/modules/ROOT/assets/images/hetzner.svg
  docs/modules/ROOT/assets/images/ibm.svg
  docs/modules/ROOT/assets/images/jelastic.svg
  docs/modules/ROOT/assets/images/mariadb.svg
  docs/modules/ROOT/assets/images/microsoft.svg
  docs/modules/ROOT/assets/images/minio.svg
  docs/modules/ROOT/assets/images/mysql.svg
  docs/modules/ROOT/assets/images/nginx.svg
  docs/modules/ROOT/assets/images/office-365.svg
  docs/modules/ROOT/assets/images/pivotal.svg
  docs/modules/ROOT/assets/images/podman.svg
  docs/modules/ROOT/assets/images/python.svg
  docs/modules/ROOT/assets/images/rancher.svg
  docs/modules/ROOT/assets/images/red-hat.svg
  docs/modules/ROOT/assets/images/salesforce.svg
  docs/modules/ROOT/assets/images/slack.svg
  docs/modules/ROOT/assets/images/switzerland.svg
Labels: change

#27 Fix branch name in Antora trigger
  .github/workflows/triggerci.yml
Labels: change

#24 Extend system idea with graphical user interface and API endpoint
  docs/modules/ROOT/assets/images/system/api.drawio.svg
  docs/modules/ROOT/assets/images/system/systemidea.drawio.svg
  docs/modules/ROOT/pages/explanation/system/details-external-services.adoc
  docs/modules/ROOT/pages/explanation/system/details-ui.adoc
  docs/modules/ROOT/pages/explanation/system/idea.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: change, requirement/functional

#30 Define decision structure
  docs/modules/ROOT/pages/references/document-decisions.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: change

#29 Rename Alternatives to Proposals
  docs/modules/ROOT/pages/explanation/decisions/arbitrary-usernames.adoc
  docs/modules/ROOT/pages/explanation/decisions/idp-group-mapping.adoc
  docs/modules/ROOT/pages/explanation/decisions/keycloak.adoc
  docs/modules/ROOT/pages/explanation/decisions/kyverno-generator.adoc
  docs/modules/ROOT/pages/explanation/decisions/kyverno-policy.adoc
  docs/modules/ROOT/pages/explanation/decisions/stable-usernames.adoc
  docs/modules/ROOT/pages/explanation/decisions/usernames.adoc
Labels: change

#28 Document arbitrary organization name requirement
  docs/modules/ROOT/pages/references/quality-requirements/usability/organization-arbitrary-name.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#31 Adjust setup instructions for production use case
  docs/modules/ROOT/pages/how-to/keycloak-setup.adoc
Labels: change

#32 Update CPU/memory/storage quotas from recent calculations
  docs/modules/ROOT/pages/references/quality-requirements/performance/resource-quota.adoc
Labels: requirement/quality

#38 Replaceability of external components
  docs/modules/ROOT/pages/explanation/system/details-external-services.adoc
  docs/modules/ROOT/pages/references/quality-requirements/portability/external-components-plugins.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality
