Repository appuio/appuio-io-docs, pull requests merged in 2021-11, with the labels that each got.

#58 Functional Requirements targeting the Portal
  docs/modules/ROOT/pages/how-to/day2ops/disable-access.adoc
  docs/modules/ROOT/pages/references/functional-requirements/portal.adoc
  docs/modules/ROOT/pages/references/glossary.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/functional

#60 Rewrite resource-quota requirement
  docs/modules/ROOT/pages/references/quality-requirements/performance/resource-quota.adoc
Labels: requirement/quality

#62 Remove Organization deletion scenario
  docs/modules/ROOT/pages/references/functional-requirements/portal.adoc
Labels: requirement/functional

#61 Correctly specify that we only consider CPU/memory limits for Terminating Pods
  docs/modules/ROOT/pages/references/quality-requirements/performance/resource-quota.adoc
Labels: ignore

#64 Describe teams in data model
  docs/modules/ROOT/assets/images/system/keycloak-model.drawio.svg
  docs/modules/ROOT/pages/references/architecture/identity-data-model.adoc
Labels: change

#65 Decision about Unit Prefixes
  docs/modules/ROOT/pages/explanation/decisions/unit-prefixes.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#66 Add how-to on overriding default resource limit for a namespace
  docs/modules/ROOT/pages/how-to/day2ops/override-default-quota.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: tutorial

#67 Fix quota annotation name
  docs/modules/ROOT/pages/how-to/day2ops/override-default-quota.adoc
Labels: change

#69 Document label/annotation allowlist
  docs/modules/ROOT/pages/references/architecture/namespace-ownership.adoc
Labels: decision

#68 Add how-to page to override namespace quota
  docs/modules/ROOT/pages/how-to/day2ops/override-namespace-quota.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: tutorial

#73 Update URLs in Keycloak client config
  docs/modules/ROOT/pages/how-to/zone-setup.adoc
Labels: tutorial

#74 Add documentation on setting a default identity provider
  docs/modules/ROOT/pages/how-to/vshn-example/keycloak-brokering.adoc
Labels: tutorial

#71 Remove org prefix from OrganizationMembers
  docs/modules/ROOT/pages/references/architecture/control-api-org.adoc
Labels: change

#75 Remove dead links
  docs/modules/ROOT/pages/explanation/decisions/control-api.adoc
Labels: change

#72 Add documentation regarding metering setup on a new zone
  docs/modules/ROOT/pages/how-to/vshn-example/activate-zone.adoc
  docs/modules/ROOT/pages/how-to/zone-setup.adoc
Labels: tutorial
