Repository appuio/appuio-io-docs, pull requests merged in 2021-12, with the labels that each got.

#76 Add how-to for setting up an OCP4 cluster which is suitable for use as an APPUiO Cloud zone
  docs/modules/ROOT/pages/how-to/zone-cluster-install.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: tutorial

#78 Rename Zone fields in Control API to match official naming convention
  docs/modules/ROOT/pages/references/architecture/control-api-zone.adoc
Labels: change

#77 Billing and Reporting Requirements
  docs/modules/ROOT/pages/references/functional-requirements/billing.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/functional

#80 Remove `org-` prefix for organization namespaces
  docs/modules/ROOT/pages/references/architecture/control-api-org.adoc
Labels: decision

#81 Add logging and registry to DNS scheme
  docs/modules/ROOT/pages/references/dns-naming-scheme.adoc
Labels: enhancement

#83 Document how to access metering data
  docs/modules/ROOT/pages/explanation/decisions/access-metering-data.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#84 Sampling rate of intermediate metering data
  docs/modules/ROOT/pages/references/quality-requirements/functional/samplinginterval-for-collecting.adoc
  docs/modules/ROOT/pages/references/quality-requirements/functional/samplinginterval-for-reporting.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#85 Decision: Document EFK stack usage
  docs/modules/ROOT/pages/explanation/decisions/efk-openshift-logging.adoc
Labels: decision

#86 Installation: Document correct infra node sizing
  docs/modules/ROOT/pages/how-to/zone-cluster-install.adoc
Labels: change

#88 Document how to measure log ingestion by organization
  docs/modules/ROOT/pages/how-to/measure-log-ingestion-by-organization.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: change

#89 Improve group clause in log ingestion query
  docs/modules/ROOT/pages/how-to/measure-log-ingestion-by-organization.adoc
Labels: change

#90 No off-the-shelf ETL processor for metering and billing
  docs/modules/ROOT/pages/explanation/decisions/billing-etl.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#79 Document model and flow of metering data for billing
  docs/modules/ROOT/assets/images/system/data-model-billing.drawio.svg
  docs/modules/ROOT/pages/references/architecture/metering-data-flow.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/functional, decision
