Repository appuio/appuio-io-docs, pull requests merged in 2021-10, with the labels that each got.

#34 Add instructions to setup APPUiO Keycloak extensions
  docs/modules/ROOT/pages/how-to/keycloak-brokering.adoc
  docs/modules/ROOT/pages/how-to/keycloak-setup.adoc
Labels: change

#40 Update brokering how-to page after prod setup
  docs/modules/ROOT/pages/how-to/keycloak-brokering.adoc
Labels: change

#35 Framework pattern for Control API
  docs/antora.yml
  docs/modules/ROOT/assets/images/decision/kubernetes-api-proposal.drawio.svg
  docs/modules/ROOT/assets/images/decision/rest-api-proposal.drawio.svg
  docs/modules/ROOT/assets/images/system/systemidea.drawio.svg
  docs/modules/ROOT/pages/explanation/decisions/control-api.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
Labels: decision

#44 Requirement of the metrics scope for invoicing
  docs/modules/ROOT/pages/references/quality-requirements/usability/metrics-scope-invoicing.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/quality

#48 Metering and invoicing architecture
  docs/modules/ROOT/assets/images/system/metering-invoicing.drawio.svg
  docs/modules/ROOT/pages/references/architecture/metering.adoc
  docs/modules/ROOT/pages/references/architecture/metrics-of-interest.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: requirement/functional
