Repository appuio/appuio-io-docs, pull requests merged in 2022-04, with the labels that each got.

#116 Fix filename in menu
  docs/modules/ROOT/partials/nav-reference.adoc
Labels: change

#119 Add instructions to setup the APPUiO Cloud Agent on a new Zone
  docs/modules/ROOT/pages/how-to/zone-cluster-install.adoc
Labels: tutorial

#118 Sub queries and fact properties
  docs/modules/ROOT/assets/images/system/data-model-billing.drawio.svg
  docs/modules/ROOT/pages/references/architecture/metering-data-flow.adoc
Labels: requirement/functional

#121 Add step for setting up APPUiO Cloud specific CNAMES
  docs/modules/ROOT/pages/how-to/zone-cluster-install.adoc
Labels: enhancement
